notes: |
  This configuration runs hyperparameter tuning for classical ML models 
  on preprocessed fMRI + metadata dataset. Uses SMOTE to handle imbalance. 
  Models include RandomForest, GradientBoosting, AdaBoost, and KNN.

### Data
root_folder: "/u/b/i/bingl/private/fMRI-AHDH"

data_preparation:
  master_seed: 3407
  enable_fmri: True # True or False --> When = False, better to have k = 0 (although the code doesn't matter)
  # Below are parameters for mutual_info: If enable_fmri = false, ignore both mutual_info and ida 
  mutual_info: True # when this is true, ida must be set to false
  k: 1000 # 100 or 1000 
  # Below are parameters for IDA: 
  ida: False # when this is true, mutual_info must be set to false 
  # params should not be changed: 
  scaler_enabled: True # This should always be true -> Dont change
  scaler: "StandardScaler" # dont change this 

output_params: 
  task: "adhd" # "four", "adhd", "sex"  
  training_enabled: True
  run_inference_on_test: True 
  aggregate_inference: True # Always set to true 
  output_inference_dir: "/u/b/i/bingl/private/fMRI-AHDH/ML_inference"

model_params: # Chose from the below model_name, unless testing for errors then no need to use "testing"
  model_name: "testing" # "LogisticRegression", "GradientBoosting", "AdaBoost", "RandomForest", "KNN", "SGDClassifier", "tesing", "SVM", "NuSMV"
  seed: 3407 # no need to change
  num_folds: 5 # no need to change

